[package]
name = "ircd2"
description = "P2P IRC daemon"
version = "0.4.0"
edition = "2021"
authors = ["darkfi <dev@dark.fi>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"
keywords = []
categories = []

[dependencies]
darkfi = {path = "../../", features = ["net", "rpc", "bs58"]}

# Async
smol = "1.2.5"
futures = "0.3.24"
futures-rustls = "0.22.2"
rustls-pemfile = "1.0.1"
async-std = "1.12.0"
async-trait = "0.1.57"
easy-parallel = "3.2.0"

# Crypto
crypto_box = "0.8.1"
rand = "0.8.5"

# Misc
clap = {version = "3.2.20", features = ["derive"]}
log = "0.4.17"
simplelog = "0.12.0"
fxhash = "0.2.1"
ctrlc = { version = "3.2.3", features = ["termination"] }
url = "2.3.1"
chrono = "0.4.22"
ripemd = "0.1.3"

# Encoding and parsing
serde_json = "1.0.85"
serde = {version = "1.0.145", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
bs58 = "0.4.0"
toml = "0.5.9"
hex = "0.4.3"
