## lilith configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

## JSON-RPC settings
[rpc]
# JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:18927"

# Disabled RPC methods
#rpc_disabled_methods = []

## Per-network settings
#[network."darkfid_testnet_v5"]
#accept_addrs = ["tcp+tls://0.0.0.0:8342"]
#seeds = []
#peers = []
#version = "0.5.0"
#app_name = "darkfid"
#localnet = false
#hostlist ="~/.local/share/darkfi/lilith/darkfid_sync/hostlist.tsv"
#datastore = "~/.local/share/darkfi/lilith/darkfid_sync"
#magic_bytes = [163, 139, 113, 101]

#[network."darkirc_v5"]
#accept_addrs = ["tcp+tls://0.0.0.0:25551"]
#seeds = []
#peers = []
#version = "0.5.1"
#app_name = "darkirc"
#localnet = false
#datastore = "~/.local/share/darkfi/lilith/darkirc"
#hostlist ="~/.local/share/darkfi/lilith/darkirc/hostlist.tsv"
#magic_bytes = [251, 229, 199, 181]

#[network."taud_v5"]
#accept_addrs = ["tcp+tls://0.0.0.0:23331"]
#seeds = []
#peers = []
#version = "0.5.0"
#app_name = "taud"
#localnet = false
#datastore = "~/.local/share/darkfi/lilith/taud"
#hostlist ="~/.local/share/darkfi/lilith/taud/hostlist.tsv"
#magic_bytes = [157, 137, 109, 97]
