## lilith configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

## JSON-RPC settings
[rpc]
# JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:18927"

# Disabled RPC methods
#rpc_disabled_methods = []

## Per-network settings
#[network."darkfid_sync_v4"]
#accept_addrs = ["tcp+tls://0.0.0.0:33022"]
#seeds = []
#peers = []
#version = "0.4.1"
#localnet = false
#hostlist ="~/.local/share/darkfi/lilith/darkfid_sync/hostlist.tsv"
#datastore = "~/.local/share/darkfi/lilith/darkfid_sync"

#[network."darkfid_consensus_v4"]
#accept_addrs = ["tcp+tls://0.0.0.0:33023"]
#seeds = []
#peers = []
#version = "0.4.1"
#localnet = false
#datastore = "~/.local/share/darkfi/lilith/darkfid_consensus"
#hostlist ="~/.local/share/darkfi/lilith/darkfid_consensus/hostlist.tsv"

#[network."darkirc_v4"]
#accept_addrs = ["tcp+tls://0.0.0.0:25551"]
#seeds = []
#peers = []
#version = "0.4.1"
#localnet = false
#datastore = "~/.local/share/darkfi/lilith/darkirc"
#hostlist ="~/.local/share/darkfi/lilith/darkirc/hostlist.tsv"

#[network."taud_v4"]
#accept_addrs = ["tcp+tls://0.0.0.0:23331"]
#seeds = []
#peers = []
#version = "0.4.1"
#localnet = false
#datastore = "~/.local/share/darkfi/lilith/taud"
#hostlist ="~/.local/share/darkfi/lilith/taud/hostlist.tsv"
