## JSON-RPC listen URL
rpc_listen="tcp://127.0.0.1:8892"

## IRC listen URL
irc_listen="tcp://127.0.0.1:22024"

## List of channels to autojoin for new client connections
autojoin = ["#dev"]

## P2P net settings
[net]
## Connection slots
outbound_connections=3

inbound = ["tcp://127.0.0.1:25554"]

external_addr = ["tcp://127.0.0.1:25554"]

peers = ["tcp://127.0.0.1:25552"]

## Seed nodes to connect to 
# seeds = ["tcp://127.0.0.1:25551"]

# Prefered transports for outbound connections
outbound_transports = ["tcp"]

localnet = true
#
# [channel."#dev"]
# topic = "DarkFi Development HQ"

# [channel."#test1"]
# secret = "HoLfk8vXBvNsBZ73e2xRPBZ9vEbnF9FVi4fDdyU9AZLU"
