[package]
name = "state_usage_analyser"
version = "0.3.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
async-std = {version = "1.12.0", features = ["attributes"]}
bincode = "2.0.0-rc.2"
darkfi = {path = "../../../", features = ["blockchain"]}
incrementalmerkletree = "0.3.0"
lazy-init = "0.5.1"
log = "0.4.17"
pasta_curves = "0.4.1"
rand = "0.8.5"
serde = {version = "1.0.150", features = ["derive"]}
sled = "0.34.7"
