rpc_listen = "tcp://127.0.0.1:25570"
irc_listen = "tcp://127.0.0.1:6669"

[net]
outbound_connections = 0
inbound = ["tls://127.0.0.1:25571"]
external_addr = ["tls://127.0.0.1:25571"]
seeds = []
peers = ["tls://127.0.0.1:25551"]

[channel."#encrypted"]
topic ="Encrypted channel"
secret = "7CkVuFgwTUpJn5Sv67Q3fyEDpa28yrSeL5Hg2GqQ4jfM"

[channel."#plain"]
topic = "Plain unencrypted channel"
