[package]
name = "genev"
description = "Generic Event example CLI"
version = "0.5.0"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://codeberg.org/darkrenaissance/darkfi"

[dependencies]
genevd = {path = "../genevd"}

darkfi = {path = "../../../", features = ["event-graph", "rpc", "bs58"]}
darkfi-serial = "0.5.0"

smol = "2.0.2"
clap = {version = "4.4.11", features = ["derive"]}
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", default-features = false, features = ["fmt"] }
tinyjson = "2.5.1"
url = "2.5.4"

[lints]
workspace = true
