[package]
name = "genev"
description = "Generic Event example CLI"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
genevd = {path = "../genevd"}

darkfi = {path = "../../../", features = ["event-graph", "rpc", "bs58"]}
darkfi-serial = {path = "../../../src/serial"}

smol = "1.3.0"
clap = {version = "4.4.13", features = ["derive"]}
log = "0.4.20"
simplelog = "0.12.1"
tinyjson = "2.5.1"
url = "2.5.0"
