[package]
name = "genev"
description = "Generic Event example CLI"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../../", features = ["event-graph", "rpc", "bs58"]}
darkfi-serial = {path = "../../../src/serial"}

async-std = {version = "1.12.0", features = ["attributes"]}
clap = {version = "4.3.17", features = ["derive"]}
libsqlite3-sys = {version = "0.26.0", features = ["bundled-sqlcipher-vendored-openssl"]}
log = "0.4.19"
simplelog = "0.12.1"
serde = {version = "1.0.173", features = ["derive"]}
serde_json = "1.0.103"
url = "2.4.0"

