## JSON-RPC listen URL
#rpc_listen="tcp://127.0.0.1:23330"

## Sets Datastore Path
#datastore="~/.tau"

## Current display name
#nickname="NICKNAME"

## Workspaces
workspaces = ["darkfi-dev:2bCqQTd8BJgeUzH7JQELZxjQuWS8aCmXZ9C6w7ktNS1v"]

# P2P network settings
[net]
## P2P accept addresses
#inbound = ["tcp+tls://127.0.0.1:23331"]

## Connection slots
outbound_connections=8

## Addresses we want to advertise to peers
## These should be reachable externally
#external_addrs = ["tcp+tls://127.0.0.1:23331"]

## Specific peers to connect to
#peers = ["tcp+tls://127.0.0.1:23331"]

## Seed nodes to connect to
seeds=["tcp+tls://lilith0.dark.fi:23331", "tcp+tls://lilith1.dark.fi:23331"]

# Whitelisted transports for outbound connections
allowed_transports = ["tcp+tls"]

# Enable transport mixing
# Allows mixing transports, e.g. tor+tls:// connecting to tcp+tls://
# By default this is not allowed.
#transport_mixing = false
