## minerd configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

# Number of nonces to execute in system hashrate benchmark
#bench = 1000

# Flag indicating whether to run miner in light mode
light_mode = false

# Flag indicating whether to run miner with Large Pages
large_pages = false

# Flag indicating whether to run miner with secure access to JIT memory (if supported)
secure = false

# PoW miner number of threads to use
threads = 2

# Polling rate to ask darkfid for mining jobs
#polling_rate = 2

# Stop mining at given height (0 mines forever)
#stop_at_height = 0

# Blockchain network to use
network = "localnet"

# Localnet blockchain network configuration
[network_config."localnet"]
# Wallet mining address to receive mining rewards.
# This is a dummy one so the miner can start,
# replace with your own one.
recipient = "9vw6WznKk7xEFQwwXhJWMMdjUPi3cXL8NrFKQpKifG1U"

# Optional contract spend hook to use in the mining reward
#spend_hook = "YOUR_SPEND_HOOK_HERE"

# Optional contract user data to use in the mining reward.
# This is not arbitrary data.
#user_data = "YOUR_USER_DATA_HERE"

# darkfid JSON-RPC endpoint
endpoint = "tcp://127.0.0.1:48340"
