## dht configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

# P2P accept addresses
#p2p_accept = ["tls://127.0.0.1:9541"]

# P2P external addresses
#p2p_external = ["tls://127.0.0.1:9541"]

# Connection slots
#slots = 8

# Seed nodes to connect to
#seed = []

# Peers to connect to
#peer = []

## JSON-RPC settings
[rpc]
# JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:9540"

# Disabled RPC methods
#rpc_disabled_methods = []
