[package]
name = "darkotc"
version = "0.3.0"
homepage = "https://dark.fi"
description = "Atomic swap commandline tool"
authors = ["darkfi <dev@dark.fi>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-std = {version = "1.12.0", features = ["attributes"]}
bs58 = "0.4.0"
clap = {version = "3.2.16", features = ["derive"]}
darkfi = {path = "../../", features = ["crypto", "rpc", "util"]}
halo2_proofs = "0.2.0"
halo2_gadgets = "0.2.0"
num-bigint = {version = "0.4.3", features = ["serde"]}
rand = "0.8.5"
serde_json = "1.0.83"
url = "2.2.2"
