[package]
name = "gatewayd"
version = "0.2.0"
edition = "2021"

[dependencies.darkfi]
path= "../../"
features = ["node", "cli"]

[dependencies]
# Async
smol = "1.2.5"
async-std = "1.10.0"
async-channel = "1.6.1"
async-executor = "1.4.1"
easy-parallel = "3.2.0"

# Misc
clap = {version = "3.0.7", features = ["derive"]}
log = "0.4.14"
num_cpus = "1.13.1"
simplelog = "0.11.2"
