#[[nodes]]
#name = "darkirc"
#host = "localhost"
#port = 26660
#type = "NORMAL"

#[[nodes]]
#name = "taud"
#host = "localhost"
#port = 23330
#type = "NORMAL"

#[[nodes]]
#name = "fud"
#host = "localhost"
#port = 9706
#type = "NORMAL"

#[[nodes]]
#name = "darkfid-testnet"
#host = "localhost"
#port = 18346
#type = "NORMAL"

#[[nodes]]
#name = "darkfid-mainnet"
#host = "localhost"
#port = 8346
#type = "NORMAL"

#[[nodes]]
#name = "darkfid-localnet"
#host = "localhost"
#port = 28346
#type = "NORMAL"

#[[nodes]]
#name = "evgrd"
#host = "localhost"
#port = 26690
#type = "NORMAL"

#[[nodes]]
#name = "lilith"
#host = "localhost"
#port = 18927
#type = "LILITH"
