[package]
name = "pqxdh"
version = "0.4.1"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
aes-gcm-siv = "0.11.1"
curve25519-dalek = {version = "4.1.3", features = ["digest", "legacy_compatibility"]}
digest = "0.10.7"
ed25519-dalek = "2.1.1"
kyber-kem = "0.1.3"
rand = "0.8.5"
sha2 = "0.10.9"
x25519-dalek = {version = "2.0.1", features = ["static_secrets"]}
