[package]
name = "snowball-consensus"
version = "0.4.1"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
darkfi = {path = "../../../", features = ["util"]}
darkfi-serial = {path = "../../../src/serial"}

blake3 = "1.8.1"
num-bigint = "0.4.6"
rand = "0.8.5"
