[package]
name = "cashierd"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path = "../../"
features = ["node", "rpc", "cli"]

[dependencies]
# Async
smol = "1.2.5"
futures = "0.3.19"
async-std = "1.10.0"
async-trait = "0.1.52"
async-channel = "1.6.1"
async-executor = "1.4.1"
easy-parallel = "3.2.0"

# Crypto
rand = "0.8.4"

# Misc
clap = {version = "3.0.7", features = ["derive"]}
log = "0.4.14"
num_cpus = "1.13.1"
simplelog = "0.11.2"
thiserror = "1.0.30"
url = "2.2.2"

# Encoding and parsing
serde = {version = "1.0.133", features = ["derive"], optional = true}
serde_json = "1.0.74"

# Bitcoin bridge dependencies
bdk = {version = "0.15.0", optional = true}
anyhow = {version = "1.0.52", optional = true}
bitcoin = {version = "0.27.1", optional = true}
secp256k1 = {version = "0.20.1", default-features = false, features = ["rand-std"], optional = true}

# Ethereum bridge dependencies
hex = {version = "0.4.3", optional = true}
hash-db = {version = "0.15.2", optional = true}
lazy_static = {version = "1.4.0", optional = true}
keccak-hasher = {version = "0.15.3", optional = true}
num-bigint = {version = "0.4.3", features = ["rand", "serde"], optional = true}

# Solana bridge dependencies
native-tls = {version = "0.2.8", optional = true}
async-native-tls = {version = "0.4.0", optional = true}
solana-client = {version = "1.8.12", optional = true}
solana-sdk = {version = "1.8.12", optional = true}
spl-associated-token-account = {version = "1.0.3", features = ["no-entrypoint"], optional = true}
spl-token = {version = "3.2.0", features = ["no-entrypoint"], optional = true}
tungstenite = {version = "0.16.0", optional = true}

[features]
btc = [
    "anyhow",
    "bdk",
    "bitcoin",
    "secp256k1",
]

eth = [
    "serde",
    "num-bigint",
    "keccak-hasher",
    "hash-db",
    "lazy_static",
    "hex",
]

sol = [
    "async-native-tls",
    "native-tls",
    "serde",
    "solana-client",
    "solana-sdk",
    "spl-associated-token-account",
    "spl-token",
    "tungstenite",
]
