[package]
name = "explorerd"
version = "0.5.0"
description = "Daemon to listen for new blocks from darkfid and store them in an easily accessible format for further usage."
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://codeberg.org/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
# Darkfi
darkfi = {path = "../../../", features = ["async-daemonize", "validator", "rpc"]}
darkfi-sdk = {path = "../../../src/sdk"}
darkfi-serial = "0.5.0"

# JSON-RPC
async-trait = "0.1.89"
tinyjson = "2.5.1"
url = "2.5.7"

# Daemon
easy-parallel = "3.3.1"
signal-hook-async-std = "0.3.0"
signal-hook = "0.3.18"
tracing-subscriber = { version = "0.3.22", default-features = false, features = ["fmt"] }
tracing-appender = "0.2.4"
smol = "2.0.2"

# Argument parsing
serde = {version = "1.0.228", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"

# Database
sled-overlay = "0.1.14"

# Misc
blake3 = "1.8.2"
tracing = "0.1.44"
lazy_static = "1.5.0"
tar = "0.4.44"
toml = "0.9.8"
thiserror = "2.0.17"

# Testing
tempdir = "0.3.7"
