[package]
name = "rln"
version = "0.4.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
darkfi-sdk = {path = "../../../src/sdk"}
darkfi = {path = "../../../", features = ["zk"]}
lazy_static = "1.4.0"
rand = "0.8.5"
