main_activity_inject = "java/MainActivity.java"
java_files = [
    "java/ForegroundService.java",
    "java/videodecode/VideoDecoder.java",
    "java/textinput/InputConnection.java",
    "java/textinput/State.java",
    "java/textinput/Listener.java",
    "java/textinput/Settings.java",
    "java/textinput/GameTextInput.java"
]
