## drk configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

# Blockchain network to use
network = "testnet"

# Flag indicating whether you want some fun in your life
fun = true

# Localnet blockchain network configuration
[network_config."localnet"]
# Path to blockchain cache database
cache_path = "~/.local/share/darkfi/drk/localnet/cache"

# Path to wallet database
wallet_path = "~/.local/share/darkfi/drk/localnet/wallet.db"

# Password for the wallet database
wallet_pass = "changeme"

# darkfid JSON-RPC endpoint
endpoint = "tcp://127.0.0.1:28345"

# Path to interactive shell history file
history_path = "~/.local/share/darkfi/drk/localnet/history.txt"

# Testnet blockchain network configuration
[network_config."testnet"]
# Path to blockchain cache database
cache_path = "~/.local/share/darkfi/drk/testnet/cache"

# Path to wallet database
wallet_path = "~/.local/share/darkfi/drk/testnet/wallet.db"

# Password for the wallet database
wallet_pass = "changeme"

# darkfid JSON-RPC endpoint
endpoint = "tcp://127.0.0.1:18345"

# Path to interactive shell history file
history_path = "~/.local/share/darkfi/drk/testnet/history.txt"

# Mainnet blockchain network configuration
[network_config."mainnet"]
# Path to blockchain cache database
cache_path = "~/.local/share/darkfi/drk/mainnet/cache"

# Path to wallet database
wallet_path = "~/.local/share/darkfi/drk/mainnet/wallet.db"

# Password for the wallet database
wallet_pass = "changeme"

# darkfid JSON-RPC endpoint
endpoint = "tcp://127.0.0.1:8345"

# Path to interactive shell history file
history_path = "~/.local/share/darkfi/drk/mainnet/history.txt"
