[package]
name = "map"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path = "../../"
features = ["rpc", "cli"]

[dependencies]
# Tui
termion = "1.5.6"
tui = "0.16.0"

# Async
smol = "1.2.4"
async-std = {version = "1.10.0", features = ["attributes"]}
easy-parallel = "3.2.0"
async-channel = "1.6.1"

# Misc
clap = "3.0.7"
rand = "0.6.5"
simplelog = "0.11.2"
log = "0.4.14"
num_cpus = "1.13.1"

# Encoding and parsing
serde_json = "1.0.74"
