[package]
name = "genevd"
description = "Generic Event example daemon"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://codeberg.org/darkrenaissance/darkfi"

[lib]
name = "genevd"
path = "src/lib.rs"

[[bin]]
name = "genevd"
path = "src/main.rs"

[dependencies]
darkfi = { path = "../../../", features = [
    "async-daemonize",
    "event-graph",
    "rpc",
] }
darkfi-serial = { path = "../../../src/serial" }

# Crypto
blake3 = "1.5.1"

# Event Graph DB
sled-overlay = "0.1.3"

# Misc
async-trait = "0.1.81"
log = "0.4.22"
tinyjson = "2.5.1"
url = "2.5.2"

# Daemon
easy-parallel = "3.3.1"
signal-hook-async-std = "0.2.2"
signal-hook = "0.3.17"
simplelog = "0.12.2"
smol = "2.0.0"

# Argument parsing
serde = { version = "1.0.204", features = ["derive"] }
structopt = "0.3.26"
structopt-toml = "0.5.1"

[lints]
workspace = true

