## Current display name
#nickname="NICKNAME"

## Sets Datastore Path
#datastore = "~/.local/share/darkfi/genev_db"

## Sets DB logs replay datastore path
#replay_datastore = "~/.local/share/darkfi/replayed_darkirc_db"

## Run in replay mode to store Sled DB instructions
## (for eventgraph debugging tool)
#replay_mode = false

## JSON-RPC settings
[rpc]
## JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:28880"

## Disabled RPC methods
rpc_disabled_methods = ["p2p.get_info"]

## net settings
[net]
## Connection slots
outbound_connections = 8

# Prefered transports for outbound connections
active_profiles = ["tcp+tls"]

[net.profiles."tcp+tls"]
## P2P accept addresses
#inbound = ["tcp+tls://127.0.0.1:28881"]

## P2P external addresses
#external_addr = ["tcp+tls://127.0.0.1:28881"]

## Peers to connect to
#peers = ["tcp+tls://127.0.0.1:28881"]

## Seed nodes to connect to
#seeds = []