## Current display name
#nickname="NICKNAME"

## Sets Datastore Path
#datastore = "~/.local/share/darkfi/genev_db"

## Sets DB logs replay datastore path
#replay_datastore = "~/.local/share/darkfi/replayed_darkirc_db"

## Run in replay mode to store Sled DB instructions
## (for eventgraph debugging tool)
#replay_mode = false

## JSON-RPC settings
[rpc]
## JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:28880"

## Disabled RPC methods
rpc_disabled_methods = ["p2p.get_info"]

## net settings
[net]
## P2P accept addresses
#inbound = ["tcp://127.0.0.1:28881"]

## Connection slots
outbound_connections = 8

## P2P external addresses
#external_addr = ["tls://127.0.0.1:28881"]

## Peers to connect to
#peers = ["tls://127.0.0.1:28881"]

## Seed nodes to connect to
seeds = ["tls://lilith0.dark.fi:28881", "tls://lilith1.dark.fi:28881"]

# Prefered transports for outbound connections
#transports = ["tls", "tcp"]

## these are the default configuration for the p2p network
#manual_attempt_limit=0
#seed_query_timeout_seconds=8
#connect_timeout_seconds=10
#channel_handshake_seconds=4
#channel_heartbeat_seconds=10
