[package]
name = "gg"
version = "0.4.1"
description = """\
Genesis Generator, a command-line utility to generate,\
display and verify a base64 encoded Darkfi genesis block\
"""
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://codeberg.org/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
# Darkfi
darkfi = {path = "../../../", features = ["bs58", "validator"]}
darkfi_money_contract = {path = "../../../src/contract/money", features = ["no-entrypoint", "client"]}
darkfi-contract-test-harness = {path = "../../../src/contract/test-harness"}
darkfi-sdk = {path = "../../../src/sdk"}
darkfi-serial = "0.5.1"

# Misc
bs58 = "0.5.1"
clap = {version = "4.4.11", features = ["derive"]}
sled-overlay = "0.1.14"
smol = "2.0.2"

[patch.crates-io]
halo2_proofs = {git="https://github.com/parazyd/halo2", branch="v031"}
halo2_gadgets = {git="https://github.com/parazyd/halo2", branch="v031"}
