[package]
name = "dhtd"
version = "0.4.1"
homepage = "https://dark.fi"
description = "DHT daemon"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://codeberg.org/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
blake3 = "1.5.4"
darkfi = {path = "../../../", features = ["dht"]}
darkfi-serial = {path = "../../../src/serial", features = ["derive", "crypto"]}
easy-parallel = "3.3.1"
log = "0.4.22"
rand = "0.8.5"
simplelog = "0.12.2"
smol = "2.0.1"
url = "2.5.2"

[lints]
workspace = true

