[package]
name = "darkwikid"
version = "0.4.1"
homepage = "https://dark.fi"
description = "Reference daemon for a decentralized P2P wiki"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-std = "1.12.0"
async-trait = "0.1.71"
blake3 = "1.4.1"
bs58 = "0.5.0"
darkfi = {path = "../../../", features = ["raft", "rpc", "util"]}
darkfi-serial = {path = "../../../src/serial"}
dryoc = "0.5.0"
easy-parallel = "3.3.0"
futures = "0.3.28"
lazy_static = "1.4.0"
log = "0.4.19"
serde = "1.0.167"
serde_derive = "1.0.167"
serde_json = "1.0.100"
signal-hook-async-std = "0.2.2"
signal-hook = "0.3.15"
simplelog = "0.12.1"
structopt = "0.3.26"
structopt-toml = "0.5.1"
smol = "1.3.0"
toml = "0.7.6"
unicode-segmentation = "1.10.1"
url = "2.4.0"
