## Sets Datastore Path
datastore = "/tmp/genev_test/datastore/seed"

## Current display name
#nickname="NICKNAME"

## JSON-RPC settings
[rpc]
## JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:28880"

## Disabled RPC methods
rpc_disabled_methods = ["p2p.get_info"]

## net settings
[net]
## Connection slots
# outbound_connections=8

## Inbound connection slots
inbound_connections = 4

# Prefered transports for outbound connections
active_profiles = ["tcp"]

[net.profiles."tcp"]
## P2P accept addresses
inbound = ["tcp://127.0.0.1:28881"]

## P2P external addresses
# external_addr = ["tls://127.0.0.1:28881"]

## Peers to connect to
#peers = ["tls://127.0.0.1:28881"]

## Seed nodes to connect to
# seeds=["tls://lilith0.dark.fi:28881", "tls://lilith1.dark.fi:28881"]
