[package]
name = "merkletree_null_benchmark"
version = "0.1.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
darkfi = {path="../../../", features=["node"]}
darkfi-sdk = {path="../../../src/sdk"}
darkfi-serial = {path="../../../src/serial"}

rand = "0.8.5"
pasta_curves = "0.4.1"
incrementalmerkletree = "0.3.0"

serde_json = "1.0.89"
