[package]
name = "zkas"
version = "0.3.0"
homepage = "https://dark.fi"
description = "Compiler for the Halo2 zkVM language used in DarkFi."
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
clap = {version = "4.0.32", features = ["derive"]}
darkfi = {path = "../../", features = ["zkas"]}
