[package]
name = "zkas"
version = "0.4.1"
homepage = "https://dark.fi"
description = "Compiler for the Halo2 zkVM language used in DarkFi."
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
arg = {git = "https://github.com/parazyd/arg"}
darkfi = {path = "../../", features = ["zkas"]}

[lints]
workspace = true

