[package]
name = "darkfi-derive-internal"
version = "0.4.1"
homepage = "https://dark.fi"
description = "Internal crate for serialization derive macros"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://codeberg.org/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = {version = "2.0.76", features = ["full", "fold"]}

[features]
default = []
async = []

[lints]
workspace = true

