[package]
name = "darkfi-derive-internal"
version = "0.4.1"
homepage = "https://dark.fi"
description = "Internal crate for serialization derive macros"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.33"
syn = {version = "2.0.29", features = ["full", "fold"]}
