[package]
name = "darkfi-derive-internal"
version = "0.3.0"
homepage = "https://dark.fi"
description = "Internal crate for serialization derive macros"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.50"
quote = "1.0.23"
syn = {version = "1.0.107", features = ["full", "fold"]}
