[package]
name = "fu"
version = "0.3.0"
homepage = "https://dark.fi"
description = "Command-line client for fud"
authors = ["darkfi <dev@dark.fi>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-std = {version = "1.12.0", features = ["attributes"]}
clap = {version = "3.2.20", features = ["derive"]}
darkfi = {path = "../../../../", features = ["util", "rpc"]}
log = "0.4.17"
serde_json = "1.0.85"
simplelog = "0.12.0"
url = "2.3.1"

[workspace]
