[book]
authors = ["DarkFi"]
language = "en"
src = "src"
title = "The DarkFi Book"
description = "DarkFi mdbook"
text-direction = "ltr"

[output.html]
<<<<<<< HEAD
default-theme = "ayu"
preferred-dark-theme = "ayu"
#theme = "theme"
additional-css = ["theme/tabs.css"]
=======
default-theme = "darkforest"
preferred-dark-theme = "darkforest"
theme = "theme"
additional-css = ["theme/tabs.css", "theme/highlight.css", "src/fonts.css"]
>>>>>>> 5a4767adc (doc: add new DarkForest mdBook theme)
additional-js = ["theme/mermaid.min.js", "theme/mermaid-init.js", "theme/zkas-highlight.js", "theme/tabs.js"]

[output.html.playground]
runnable = false

[preprocessor.tabs]
<<<<<<< HEAD
=======
optional = true
>>>>>>> 5a4767adc (doc: add new DarkForest mdBook theme)

[preprocessor.katex]
macros = "latex-macros.txt"
after = ["links"]
optional = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
optional = true

[preprocessor.mermaid]
command = "mdbook-mermaid"
<<<<<<< HEAD
=======
optional = true
>>>>>>> 5a4767adc (doc: add new DarkForest mdBook theme)

