[book]
authors = ["DarkFi"]
language = "en"
multilingual = false
src = "src"
title = "The DarkFi Book"

[output.html]
copy-fonts = true
default-theme = "ayu"
preferred-dark-theme = "ayu"
theme = "theme"
additional-js = ["theme/mermaid.min.js", "theme/mermaid-init.js", "theme/zkas-highlight.js"]

[output.html.playground]
runnable = false

[preprocessor.katex]
macros = "latex-macros.txt"
after = ["links"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
