[package]
name = "ircd"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path = "../../"
features = ["net", "rpc"]

[dependencies]
# Async
smol = "1.2.5"
futures = "0.3.19"
async-std = "1.10.0"
async-trait = "0.1.52"
async-channel = "1.6.1"
async-executor = "1.4.1"

# Crypto
rand = "0.8.4"

# Misc
clap = "3.0.7"
log = "0.4.14"
simplelog = "0.11.2"

# Encoding and parsing
serde_json = "1.0.74"
