## JSON-RPC listen URL
#rpc_listen="tcp://127.0.0.1:11055"

## IRC listen URL
#irc_listen="tcp://127.0.0.1:11066"

## List of channels to autojoin for new client connections
autojoin = ["#dev"]

## P2P net settings
[net]
## P2P accept address
#inbound="tls://127.0.0.1:11002" 

## Connection slots
outbound_connections=5

## P2P external address
#external_addr="tls://127.0.0.1:11002"

## Peers to connect to
#peers=["tls://127.0.0.1:11003"]

## Seed nodes to connect to 
seeds=["tls://irc0.dark.fi:11001", "tls://irc1.dark.fi:11001"]

## these are the default configuration for the p2p network
#manual_attempt_limit=0
#seed_query_timeout_seconds=8
#connect_timeout_seconds=10
#channel_handshake_seconds=4
#channel_heartbeat_seconds=10

## Per-channel settings
#[channel."#dev"]
## Create with `ircd --gen-secret`
#secret = "7CkVuFgwTUpJn5Sv67Q3fyEDpa28yrSeL5Hg2GqQ4jfM"
## Topic to set for the channel
#topic = "DarkFi Development HQ"
