## IRC listen URL
irc_listen = "tcp://127.0.0.1:11065"

## Sets Datastore Path
datastore = "~/.config/darkfi/darkirc-seed"

## JSON-RPC settings
[rpc]
## JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:8000"

## Disabled RPC methods
rpc_disabled_methods = ["p2p.get_info"]

## Raft net settings
[net]
# Magic Bytes to distinguish the p2p network
magic_bytes = [251, 229, 199, 181]

## Connection slots
# outbound_connections=5

# Whitelisted transports for outbound connections
active_profiles = ["tcp"]

[net.profiles."tcp"]
## P2P accept addresses
inbound = ["tcp://127.0.0.1:11001"]

## Seed nodes to connect to
# seeds=["tcp://127.0.0.1:11002"]

## P2P external addresses
# external_addr=["tcp://127.0.0.1:11001"]

## Peers to connect to
# peers=["tcp://127.0.0.1:11001"]