[package]
name = "rpc_client_notifications"
version = "0.1.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
async-std = "1.12.0"
darkfi = {path = "../../../", features = ["rpc"]}
futures = "0.3.25"
serde_json = "1.0.89"
url = {version = "2.3.1", features = ["serde"]}
