[package]
name = "fu"
description = "Command-line client for fud"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../../", features = ["util", "rpc"]}

# Async
async-std = {version = "1.12.0", features = ["attributes"]}

# Misc
clap = {version = "4.3.11", features = ["derive"]}
libsqlite3-sys = {version = "0.26.0", features = ["bundled-sqlcipher-vendored-openssl"]}
log = "0.4.19"
serde_json = "1.0.100"
simplelog = "0.12.1"
url = "2.4.0"
