[package]
name = "fu"
description = "Command-line client for fud"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../../", features = ["util", "rpc"]}

# Async
async-std = {version = "1.12.0", features = ["attributes"]}

# Misc
clap = {version = "4.5.1", features = ["derive"]}
log = "0.4.21"
serde_json = "1.0.114"
simplelog = "0.12.2"
url = "2.5.0"
