[package]
name = "fu"
description = "Command-line client for fud"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://codeberg.org/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../../", features = ["util", "rpc"]}

# Async
async-std = {version = "1.13.0", features = ["attributes"]}

# Misc
clap = {version = "4.4.11", features = ["derive"]}
log = "0.4.26"
serde_json = "1.0.139"
simplelog = "0.12.2"
url = "2.5.4"

[lints]
workspace = true

