[package]
name = "swapd"
version = "0.4.1"
homepage = "https://dark.fi"
description = "Atomic Swap Daemon"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
darkfi = {path = "../../", features = ["async-daemonize", "async-serial", "system", "util", "net", "rpc", "sled"]}
darkfi-serial = {path = "../../src/serial", features = ["async"]}

# Misc
log = "0.4.21"

# Encoding
url = "2.5.0"

# Database
sled = "0.34.7"

# Daemon
easy-parallel = "3.3.1"
signal-hook-async-std = "0.2.2"
signal-hook = "0.3.17"
simplelog = "0.12.2"
smol = "1.3.0"

# Argument parsing
serde = {version = "1.0.197", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"

async-watch = "0.3.1"
eyre = "0.6"
ethers = { version = "2.0", features = ["ethers-solc", "ws"] }
thiserror = "1.0.57"

[dev-dependencies]
swapd = { path = ".", features = ["test-utils"] }
async-std = {version = "1.12.0", features = ["attributes", "tokio1"]}

[features]
default = []
test-utils = []
