[package]
name = "x3dh"
version = "0.4.1"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
sha2 = "0.10.6"
digest = "0.10.6"
rand = "0.8.5"
aes-gcm-siv = "0.11.1"
curve25519-dalek = {version = "4.0.0-rc.1", features = ["digest"]}
ed25519-dalek = "2.0.0-pre.0"
x25519-dalek = "2.0.0-pre.1"
