[package]
name = "x3dh"
version = "0.4.1"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
sha2 = "0.10.8"
digest = "0.10.7"
rand = "0.8.5"
aes-gcm-siv = "0.11.1"
curve25519-dalek = {version = "4.1.1", features = ["digest", "legacy_compatibility"]}
ed25519-dalek = "2.1.0"
x25519-dalek = {version = "2.0.0", features = ["static_secrets"]}
