## lilith configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

# Daemon published url, common for all enabled networks
url = ["tls://127.0.0.1"]

# Hosts .tsv file to use
hosts_file="lilith_hosts.tsv"

# JSON-RPC settings
[rpc]
# JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:18927"

# Disabled RPC methods
#rpc_disabled_methods = []

## Per-network settings
#[network."darkfid_sync"]
#port = 33032
#seeds = []
#peers = []
#localnet = true
#channel_log = true

#[network."darkfid_consensus"]
#port = 33033
#seeds = []
#peers = []
#localnet = true
#channel_log = true

#[network."darkirc"]
#port = 25551
#seeds = []
#peers = []
#localnet = true
#channel_log = true

#[network."taud"]
#port = 23331
#seeds = []
#peers = []
#localnet = true
#channel_log = true

[network."fud"]
port = 13337
#seeds = []
#peers = []
localnet = true
channel_log = true
