[package]
name = "rlnd"
version = "0.4.1"
description = "DarkFi RLN state management daemon."
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://codeberg.org/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
# Darkfi
darkfi = {path = "../../../../", features = ["async-daemonize", "async-sdk", "rpc", "sled-overlay"]}
darkfi-sdk = {path = "../../../../src/sdk"}
darkfi-serial = {path = "../../../../src/serial"}

# Misc
bs58 = "0.5.1"
sled-overlay = "0.1.19"
tracing = "0.1.44"

# JSON-RPC
async-trait = "0.1.89"
tinyjson = "2.5.1"
url = "2.5.7"

# Daemon
async-std = {version = "1.13.2", features = ["attributes"]}
easy-parallel = "3.3.1"
signal-hook-async-std = "0.4.0"
signal-hook = "0.4.1"
tracing-subscriber = { version = "0.3.22", default-features = false, features = ["fmt"] }
tracing-appender = "0.2.4"
smol = "2.0.2"

# Argument parsing
serde = {version = "1.0.228", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
