## IRC listen URL
irc_listen = "tcp://127.0.0.1:22023"

## How many DAGs to be synced (each DAG represents a 1hr msg history),
## increasing this number means you get/sync previous hours msg history 
## as well (max. 24)
dags_count = 1

## Sets Datastore Path
datastore = "darkirc2"

## List of channels to autojoin for new client connections
autojoin = ["#dev", "#test"]

# Log to file. Off by default.
log = "/tmp/darkirc2.log"
# Set log level. 1 is info (default), 2 is debug, 3 is trace
#verbose = 2

## Running darkirc in header-only mode
## history won't be fetched but DAG sync fast
#fast_mod = false

## JSON-RPC settings
[rpc]
## JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:8891"

## Disabled RPC methods
#rpc_disabled_methods = ["p2p.get_info"]

## P2P net settings
[net]
## Connection slots
outbound_connections = 8

## Inbound connection slots
# inbound_connections = 8

localnet = true
hostlist = "darkirc2/hostlist.tsv"

# Prefered transports for outbound connections
active_profiles = ["tcp"]

[net.profiles."tcp"]
## Seed nodes to connect to
seeds = ["tcp://127.0.0.1:25551"]

# inbound = ["tcp://127.0.0.1:25553"]

# external_addrs = ["tcp://127.0.0.1:25553"]

# peers = ["tcp://127.0.0.1:25552"]

#
# [channel."#dev"]
# topic = "DarkFi Development HQ"

[channel."#test"]
secret = "HoLfk8vXBvNsBZ73e2xRPBZ9vEbnF9FVi4fDdyU9AZLU"

[contact."node1"]
dm_chacha_public = "BmUo88RJ5TyR7gUWnr6Mk7tqZE5xPuCqJdJV8KWzsagh"
my_dm_chacha_secret = "JwsF8D2xvr9ff3Z5j1rhUCBL8odhdZR7qvR2qJ1ZV6P"
#my_dm_chacha_public = "ACaVU2uf4n2cheRHFP7RB9PASLweBJNdp5QJ4PGwVz67"
