## IRC listen URL
irc_listen = "tcp://127.0.0.1:22022"

## Sets Datastore Path
datastore = "darkirc1"

## List of channels to autojoin for new client connections
autojoin = ["#dev", "#test"]

# Log to file. Off by default.
#log = "/tmp/darkirc1.log"
# Set log level. 1 is info (default), 2 is debug, 3 is trace
#verbose = 2

## JSON-RPC settings
[rpc]
## JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:8890"

## Disabled RPC methods
#rpc_disabled_methods = ["p2p.get_info"]

## P2P net settings
[net]
## Connection slots
outbound_connections = 8

## Inbound connection slots
inbound_connections = 8

inbound = ["tcp://127.0.0.1:25552"]

external_addrs = ["tcp://127.0.0.1:25552"]

# peers = []

## Seed nodes to connect to 
seeds = ["tcp://127.0.0.1:25551"]

# Prefered transports for outbound connections
allowed_transports = ["tcp"]

localnet = true
hostlist = "darkirc1/hostlist.tsv"

#
# [channel."#dev"]
# topic = "DarkFi Development HQ"

[channel."#test"]
secret = "HoLfk8vXBvNsBZ73e2xRPBZ9vEbnF9FVi4fDdyU9AZLU"

[contact."node2"]
dm_chacha_public = "ACaVU2uf4n2cheRHFP7RB9PASLweBJNdp5QJ4PGwVz67"
my_dm_chacha_secret = "Bwdhe48rKsqFwGUquQSSGZZS5NQP1szrdJUhyDE77Br6"
#my_dm_chacha_public = "BmUo88RJ5TyR7gUWnr6Mk7tqZE5xPuCqJdJV8KWzsagh"
