## JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:8893"

## IRC listen URL
irc_listen = "tcp://127.0.0.1:22025"

## How many DAGs to be synced (currently each DAG represents a 24hr msg
## history counting from UTC midnight), increasing this number means 
## you get/sync previous days msg history as well (max. 5) 
dags_count = 3

## Sets Datastore Path
datastore = "darkirc4"

## List of channels to autojoin for new client connections
autojoin = ["#dev", "#test"]

# Log to file. Off by default.
#log = "/tmp/darkirc4.log"
# Set log level. 1 is info (default), 2 is debug, 3 is trace
#verbose = 2

## P2P net settings
[net]
## Connection slots
outbound_connections = 8

## Inbound connection slots
# inbound_connections = 8

# inbound = ["tcp://127.0.0.1:25555"]

# external_addrs = ["tcp://127.0.0.1:25555"]

# peers = ["tcp://127.0.0.1:25554"]

## Seed nodes to connect to
seeds = ["tcp://127.0.0.1:25551"]

# Prefered transports for outbound connections
allowed_transports = ["tcp"]

localnet = true
hostlist = "darkirc4/hostlist.tsv"

#
# [channel."#dev"]
# topic = "DarkFi Development HQ"

[channel."#test"]
secret = "HoLfk8vXBvNsBZ73e2xRPBZ9vEbnF9FVi4fDdyU9AZLU"
