## IRC listen URL
irc_listen = "tcp://127.0.0.1:22024"

## How many DAGs to be synced (each DAG represents a 1hr msg history),
## increasing this number means you get/sync previous hours msg history 
## as well (max. 24)
dags_count = 1

## Sets Datastore Path
datastore = "darkirc3"

## List of channels to autojoin for new client connections
autojoin = ["#dev", "#test"]

# Log to file. Off by default.
log = "/tmp/darkirc3.log"
# Set log level. 1 is info (default), 2 is debug, 3 is trace
#verbose = 2

## Running darkirc in header-only mode
## history won't be fetched but DAG sync fast
#fast_mod = false

## JSON-RPC settings
[rpc]
## JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:8892"

## Disabled RPC methods
#rpc_disabled_methods = ["p2p.get_info"]

## P2P net settings
[net]
## Connection slots
outbound_connections = 8

## Inbound connection slots
# inbound_connections = 8

localnet = true
hostlist = "darkirc3/hostlist.tsv"

# Prefered transports for outbound connections
active_profiles = ["tcp"]

[net.profiles."tcp"]
## Seed nodes to connect to
seeds = ["tcp://127.0.0.1:25551"]

# inbound = ["tcp://127.0.0.1:25554"]

# external_addrs = ["tcp://127.0.0.1:25554"]

# peers = ["tcp://127.0.0.1:25552"]

#
# [channel."#dev"]
# topic = "DarkFi Development HQ"

[channel."#test"]
secret = "HoLfk8vXBvNsBZ73e2xRPBZ9vEbnF9FVi4fDdyU9AZLU"
