[package]
name = "fud"
version = "0.3.0"
homepage = "https://dark.fi"
description = "File-sharing Utility Daemon, using DHT for records discovery."
authors = ["darkfi <dev@dark.fi>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-channel = "1.7.1"
async-executor = "1.4.1"
async-std = "1.12.0"
async-trait = "0.1.57"
blake3 = "1.3.1"
ctrlc = { version = "3.2.3", features = ["termination"] }
darkfi = {path = "../../../../", features = ["dht"]}
easy-parallel = "3.2.0"
futures-lite = "1.12.0"
log = "0.4.17"
serde_json = "1.0.85"
simplelog = "0.12.0"
url = "2.3.1"

# Argument parsing
serde = "1.0.145"
serde_derive = "1.0.145"
structopt = "0.3.26"
structopt-toml = "0.5.1"

[workspace]
