[package]
name = "darkwiki"
description = "CLI utility for interacting with darkwikid"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies]
darkfi = {path = "../../../", features = ["rpc"]}

# Async
smol = "1.3.0"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.71"
async-channel = "1.9.0"
futures = "0.3.28"

# Misc
log = "0.4.19"
simplelog = "0.12.1"
rand = "0.8.5"
url = "2.4.0"

# Encoding and parsing
serde = {version = "1.0.167", features = ["derive"]}
serde_json = "1.0.100"
structopt = "0.3.26"
