[package]
name = "dao"
version = "0.3.0"
homepage = "https://dark.fi"
description = "CLI utility for interacting with daod"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies.darkfi]
path = "../../../"
features = ["rpc"]

[dependencies]
# Async
smol = "1.3.0"
futures = "0.3.25"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.59"
async-channel = "1.8.0"
async-executor = "1.5.0"

# Misc
clap = {version = "4.0.29", features = ["derive"]}
log = "0.4.17"
num_cpus = "1.14.0"
simplelog = "0.12.0"
url = "2.3.1"
prettytable-rs = "0.9.0"

# Encoding and parsing
serde_json = "1.0.89"
