[package]
name = "dao"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path = "../../../"
features = ["rpc"]

[dependencies]
# Async
smol = "1.2.5"
futures = "0.3.24"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.57"
async-channel = "1.7.1"
async-executor = "1.4.1"

# Misc
clap = {version = "3.2.20", features = ["derive"]}
log = "0.4.17"
num_cpus = "1.13.1"
simplelog = "0.12.0"
url = "2.2.2"
prettytable-rs = "0.9.0"

# Encoding and parsing
serde_json = "1.0.85"
