[package]
name = "darkfid2"
version = "0.3.0"
homepage = "https://dark.fi"
description = "DarkFi node daemon"
authors = ["darkfi <dev@dark.fi>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-channel = "1.6.1"
async-executor = "1.4.1"
async-std = "1.11.0"
async-trait = "0.1.53"
chrono = "0.4.19"
ctrlc-async = {version = "3.2.2", default-features = false, features = ["async-std", "termination"]}
darkfi = {path = "../../", features = ["blockchain", "wallet", "rpc", "net", "node"]}
easy-parallel = "3.2.0"
futures-lite = "1.12.0"
fxhash = "0.2.1"
lazy-init = "0.5.0"
log = "0.4.16"
num-bigint = {version = "0.4.3", features = ["serde"]}
rand = "0.8.5"
serde_json = "1.0.79"
simplelog = "0.12.0"
sled = "0.34.7"
url = "2.2.2"

# Argument parsing
serde = "1.0.136"
serde_derive = "1.0.136"
structopt = "0.3.26"
structopt-toml = "0.5.0"
