[package]
name = "daod"
version = "0.3.0"
homepage = "https://dark.fi"
description = "DarkFi DAO daemon"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
darkfi = {path = "../../../", features = ["rpc", "crypto", "tx"]}
darkfi-sdk = {path = "../../../src/sdk"}
darkfi-serial = {path = "../../../src/serial"}

# Async
smol = "1.2.5"
futures = "0.3.25"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.58"
async-channel = "1.7.1"
async-executor = "1.4.1"
easy-parallel = "3.2.0"

# Misc
log = "0.4.17"
num_cpus = "1.14.0"
simplelog = "0.12.0"
thiserror = "1.0.37"

# Crypto
halo2_gadgets = "0.2.0"
halo2_proofs = "0.2.0"
rand = "0.8.5"
chacha20poly1305 = "0.10.1"
pasta_curves = "0.4.1"
incrementalmerkletree = "0.3.0"

# Encoding and parsing
serde_json = "1.0.87"
bs58 = "0.4.0"
fxhash = "0.2.1"

# Utilities
lazy_static = "1.4.0"
url = "2.3.1"
