[package]
name = "daod"
version = "0.3.0"
edition = "2021"

[dependencies.darkfi]
path = "../../../"
features = ["rpc", "crypto", "tx", "node"]

[dependencies]
# Async
smol = "1.2.5"
futures = "0.3.24"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.57"
async-channel = "1.7.1"
async-executor = "1.4.1"
easy-parallel = "3.2.0"

# Misc
log = "0.4.17"
num_cpus = "1.13.1"
simplelog = "0.12.0"
thiserror = "1.0.34"

# Crypto
incrementalmerkletree = "0.3.0"
pasta_curves = "0.4.0"
halo2_gadgets = "0.2.0"
halo2_proofs = "0.2.0"
rand = "0.8.5"
crypto_api_chachapoly = "0.5.0"
group = "0.12.0"

# Encoding and parsing
serde_json = "1.0.85"
bs58 = "0.4.0"

# Utilities
lazy_static = "1.4.0"
url = "2.2.2"
