[package]
name = "dchat"
version = "0.1.0"
homepage = "https://dark.fi"
description = "Demo chat app used to document DarkFi networking code"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

# ANCHOR: darkfi
[dependencies]
darkfi = {path = "../../", features = ["net", "rpc"]}
darkfi-serial = {path = "../../src/serial"}
# ANCHOR_END: darkfi

# ANCHOR: dependencies
async-std = "1.12.0"
async-trait = "0.1.59"
easy-parallel = "3.2.0"
smol = "1.3.0"
num_cpus = "1.14.0"

log = "0.4.17"
simplelog = "0.12.0"
url = "2.3.1"

serde_json = "1.0.89"
serde = {version = "1.0.148", features = ["derive"]}
toml = "0.5.9"
# ANCHOR_END: dependencies
