[package]
name = "last_man_standing"
version = "0.3.0"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[workspace]

[dependencies]
async-std = "1.12.0"
dashu = { version = "0.2.0", git = "https://github.com/ertosns/dashu" }
darkfi = {path = "../../../", features = ["blockchain"]}
darkfi-sdk = {path = "../../../src/sdk"}
rand = "0.8.5"
sled = "0.34.7"
