[package]
name = "darkfi-contract-test-harness"
version = "0.4.1"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
darkfi = {path = "../../../", features = ["validator"]}
darkfi-sdk = {path = "../../../src/sdk"}
darkfi-serial = {version = "0.4.2", features = ["crypto"]}

darkfi_dao_contract = {path = "../dao", features = ["client", "no-entrypoint"]}
darkfi_money_contract = {path = "../money", features = ["client", "no-entrypoint"]}
darkfi_deployooor_contract = {path = "../deployooor", features = ["client", "no-entrypoint"]}

num-bigint = "0.4.6"
blake3 = "1.5.5"
log = "0.4.25"
rand = "0.8.5"
simplelog = "0.12.2"
sled-overlay = "0.1.6"

[lints]
workspace = true
