[package]
name = "darkfi-contract-test-harness"
version = "0.4.1"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
darkfi = {path = "../../../", features = ["validator"]}
darkfi-sdk = {path = "../../../src/sdk"}
darkfi-serial = {path = "../../../src/serial", features = ["crypto"]}
darkfi_dao_contract = {path = "../dao", features = ["client", "no-entrypoint"]}
darkfi_money_contract = {path = "../money", features = ["client", "no-entrypoint"]}
darkfi_deployooor_contract = {path = "../deployooor", features = ["client", "no-entrypoint"]}

num-bigint = "0.4.4"
blake3 = "1.5.0"
bs58 = "0.5.0"
log = "0.4.20"
rand = "0.8.5"
simplelog = "0.12.1"
sled = "0.34.7"
