## darkfid configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

# Blockchain network to use
network = "localnet"

# Localnet blockchain network configuration
[network_config."localnet"]
# Path to the blockchain database directory
database = "darkfid0"

# Confirmation threshold, denominated by number of blocks
threshold = 6

# PoW block production target, in seconds
pow_target = 60

# Optional fixed PoW difficulty, used for testing
#pow_fixed_difficulty = 1

# Skip syncing process and start node right away
skip_sync = true

# Disable transaction's fee verification, used for testing
skip_fees = false

# Optional sync checkpoint height
#checkpoint_height = 0

# Optional sync checkpoint hash
#checkpoint = ""

## Localnet JSON-RPC settings
[network_config."localnet".rpc]
# JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:48345"

# Disabled RPC methods
#rpc_disabled_methods = ["p2p.get_info"]

## Localnet JSON-RPC settings for stratum mining requests (optional)
[network_config."localnet".stratum_rpc]
# JSON-RPC listen URL (stratum mining)
rpc_listen = "tcp://127.0.0.1:48346"

## Localnet P2P network settings
[network_config."localnet".net]
# Allow localnet hosts
localnet = true

# Whitelisted network transports for outbound connections
active_profiles = ["tcp+tls"]

[network_config."localnet".net.profiles."tcp+tls"]
# P2P accept addresses the instance listens on for inbound connections
inbound = ["tcp+tls://0.0.0.0:48340"]
