[package]
name = "darkwiki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darkfi = {path = "../../../", features = ["raft"]}


# Async
smol = "1.2.5"
async-std = {version = "1.12.0", features = ["attributes"]}
async-trait = "0.1.56"
async-channel = "1.6.1"
async-executor = "1.4.1"
easy-parallel = "3.2.0"
futures = "0.3.21"

# Misc
log = "0.4.17"
simplelog = "0.12.0"
rand = "0.8.5"
chrono = "0.4.19"
thiserror = "1.0.31"
ctrlc-async = {version= "3.2.2", default-features = false, features = ["async-std", "termination"]}
url = "2.2.2"
fxhash = "0.2.1"

# Encoding and parsing
serde = {version = "1.0.138", features = ["derive"]}
serde_json = "1.0.82"
structopt = "0.3.26"
structopt-toml = "0.5.0"
unicode-segmentation = "1.9.0"
crypto_box = {version = "0.7.2", features = ["std"]}
hex = "0.4.3"
bs58 = "0.4.0"


[workspace]

[[bin]]
name = "darkwikid"
path = "src/main.rs"

[[bin]]
name = "darkwikiupdate"
path = "src/update_cli.rs"


