[package]
name = "faucetd"
version = "0.4.1"
homepage = "https://dark.fi"
description = "DarkFi faucet daemon"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://github.com/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
async-trait = "0.1.71"
blake3 = "1.4.1"
chrono = "0.4.26"
darkfi = {path = "../../", features = ["blockchain", "wallet", "rpc", "net", "zkas"]}
darkfi-serial = {path = "../../src/serial"}
darkfi-sdk = {path = "../../src/sdk"}
darkfi-money-contract = {path = "../../src/contract/money", features = ["no-entrypoint", "client"]}
log = "0.4.19"
rand = "0.8.5"
rusqlite = "0.29.0"
serde_json = "1.0.100"
sled = "0.34.7"
url = "2.4.0"

# Daemon
async-std = "1.12.0"
easy-parallel = "3.3.0"
signal-hook-async-std = "0.2.2"
signal-hook = "0.3.15"
simplelog = "0.12.1"
smol = "1.3.0"

# Argument parsing
serde = {version = "1.0.171", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
