## faucetd configuration file
##
## Please make sure you go through all the settings so you can configure
## your daemon properly.
##
## The default values are left commented. They can be overridden either by
## uncommenting, or by using the command-line.

# Chain to use (testnet, mainnet)
#chain = "testnet"

# Path to the wallet database
#wallet_path = "~/.config/darkfi/faucetd_wallet.db"

# Password for the wallet database
#wallet_pass = "changeme"

# Path to the blockchain database directory
#database = "~/.config/darkfi/faucetd_blockchain"

# JSON-RPC listen URL
#rpc_listen = "tcp://127.0.0.1:8340"

# P2P accept addresses for the syncing protocol
#sync_p2p_accept = ["tls://127.0.0.1:9342"]

# P2P external addresses for the syncing protocol
#sync_p2p_external = ["tls://127.0.0.1:9342"]

# Connection slots for the syncing protocol
#sync_slots = 8

# Seed nodes to connect to for the syncing protocol
#sync_p2p_seed = []

# Peers to connect to for the syncing protocol
#sync_p2p_peer = []

# Prefered transports of outbound connections for the syncing protocol
#sync_p2p_transports = ["tls", "tcp"]

# Enable localnet hosts
#localnet = false

# Enable channel log
#channel_log = false

# Airdrop timeout limit in seconds
#airdrop_timeout = 600

# Airdrop amount limit
#airdrop_limit = "10"
