[package]
name = "dnetview"
description = "P2P network monitoring TUI utility"
version = "0.3.0"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies.darkfi]
path = "../../"
features = ["rpc"]

[dependencies]
# Tui
termion = "2.0.1"
tui = {version = "0.19.0", features = ["termion"]}

# Async
smol = "1.2.5"
async-std = {version = "1.12.0", features = ["attributes"]}
easy-parallel = "3.2.0"
async-channel = "1.7.1"

# Misc
clap = {version = "4.0.28", features = ["derive"]}
rand = "0.8.5"
simplelog = "0.12.0"
log = "0.4.17"
num_cpus = "1.14.0"
url = "2.3.1"
fxhash = "0.2.1"
thiserror = "1.0.37"

# Encoding and parsing
serde_json = "1.0.89"
serde = {version = "1.0.148", features = ["derive"]}
hex = "0.4.3"
