[package]
name = "dnetview"
description = "P2P network monitoring TUI utility"
version = "0.4.1"
edition = "2021"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
license = "AGPL-3.0-only"
homepage = "https://dark.fi"
repository = "https://github.com/darkrenaissance/darkfi"

[dependencies.darkfi]
path = "../../"
features = ["rpc"]

[dependencies]
# Tui
termion = "2.0.1"
tui = {version = "0.19.0", features = ["termion"]}

# Async
smol = "1.3.0"
async-std = {version = "1.12.0", features = ["attributes"]}
easy-parallel = "3.3.0"
async-channel = "1.9.0"

# Misc
clap = {version = "4.3.11", features = ["derive"]}
rand = "0.8.5"
simplelog = "0.12.1"
libsqlite3-sys = {version = "0.26.0", features = ["bundled-sqlcipher-vendored-openssl"]}
log = "0.4.19"
url = "2.4.0"
thiserror = "1.0.43"

# Encoding and parsing
serde_json = "1.0.100"
serde = {version = "1.0.171", features = ["derive"]}
hex = "0.4.3"
