## map configuration file
##
## Please make sure you go through all the settings so you can configure
## map properly.

[[nodes]]
name = "Node 1"
rpc_url = "tcp://127.0.0.1:8000"

[[nodes]]
name = "Node 2"
rpc_url = "tcp://127.0.0.1:7777"

[[nodes]]
name = "Node 3"
rpc_url = "tcp://127.0.0.1:1234"

