# dchat toml

## JSON-RPC settings
[rpc]
## JSON-RPC listen URL
rpc_listen = "tcp://127.0.0.1:53345"

## Disabled RPC methods
#rpc_disabled_methods = ["p2p.get_info"]

[net]
## Outbound connect slots. Required for outbound nodes.
outbound_connections = 5

# Set to true if testing on localhost
localnet = true

# Prefered transports for outbound connections
active_profiles = ["tcp"]

[net.profiles."tcp"]
## P2P accept addresses Required for inbound nodes.
inbound=["tcp://127.0.0.1:33448"]

## P2P external addresses. Required for inbound nodes.
external_addrs=["tcp://127.0.0.1:33448"]

## Seed nodes to connect to. Required for inbound and outbound nodes.
seeds=["tcp://127.0.0.1:44448"]
