[package]
name = "minerd"
version = "0.5.0"
homepage = "https://dark.fi"
description = "Darkfi mining daemon"
authors = ["Dyne.org foundation <foundation@dyne.org>"]
repository = "https://codeberg.org/darkrenaissance/darkfi"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
libc = "0.2.178"
parking_lot = "0.12.5"
once_cell = "1.21.3"

# Darkfi
darkfi = {path = "../../", features = ["async-daemonize", "validator", "rpc", "bs58"]}
darkfi-sdk = {path = "../../src/sdk"}
darkfi-serial = {version = "0.5.0", features = ["async"]}

# Misc
bs58 = "0.5.1"
randomx = {git = "https://codeberg.org/darkrenaissance/RandomX"}
tracing = "0.1.44"
num-bigint = "0.4.6"

# JSON-RPC
tinyjson = "2.5.1"
url = "2.5.7"

# Daemon
easy-parallel = "3.3.1"
signal-hook-async-std = "0.3.0"
signal-hook = "0.3.18"
tracing-subscriber = { version = "0.3.22", default-features = false, features = ["fmt"] }
tracing-appender = "0.2.4"
smol = "2.0.2"

# Argument parsing
serde = {version = "1.0.228", features = ["derive"]}
structopt = "0.3.26"
structopt-toml = "0.5.1"
toml = "0.9.8"

[lints]
workspace = true
