rpc_listen="tcp://127.0.0.1:10300"
verbose = 2

[net]
hostlist = "example/seed.tsv"
magic_bytes=[127, 64, 12, 201]
localnet = true
active_profiles = ["tcp"]

[net.profiles."tcp"]
inbound=["tcp://[::]:10200"]
seeds=[]
# no outbounds for seed node
